### ISSUE TITLE
学习CSS

### ISSUE THREAD

**Issue by bogeisarookie** [bogeisarookie/articles#8]
### flex-direction
```css
.container {
  flex-direction: row | row-reverse | column | column-reverse;
}
```
### flex-wrap
```css
.container{
  flex-wrap: nowrap | wrap | wrap-reverse;
}
```
### flex-flow
flex-flow是flex-direction和flex-wrap属性的缩写形式。默认值是row,nowrap。
```css
flex-flow: <‘flex-direction’> || <‘flex-wrap’>
```
### justify-content
```css
.container {
  justify-content: flex-start | flex-end | center | space-between | space-around;
}
```

- flex-start: 默认值，朝主轴开始的方向对齐。

- flex-end:朝主轴结束的方向对齐。

- center:沿主轴方向居中。

- space-between:沿主轴两端对齐，第一个子元素在主轴起点，最后一个子元素在主轴终点。

- space-around:沿主轴子元素之间均匀分布。要注意的是子元素看起来间隙是不均匀的，第一个子元素和最后一个子元素离父元素的边缘有一个单位的间隙，但两个子元素之间有两个单位的间隙，因为每个子元素的两侧都有一个单位的间隙。
### align-items
```css
.container {
  align-items: flex-start | flex-end | center | baseline | stretch;
}
```
- flex-start: 按照交叉轴的起点对齐。

- flex-end: 按照交叉轴的终点对齐。

- center: 沿交叉轴方向居中。

- baseline: 按照项目的第一行文字的基线对齐。

- stretch: 默认值，在满足子项目所设置的min-height、max-height、height的情况下拉伸子元素使之填充整个父元素。
### order
```css
.item {
  order: <integer>;//越小越排在前面
}
```
### flex-grow
```css
.item {
  flex-grow: <number>; /* default 0 */
}
```
代表是否延伸，默认0代表不延伸，1代表等分剩余空间，2代表尽量获得自己2倍的长度
### flex-shrink
```css
.item {
  flex-shrink: <number>; /* default 1 */
}
```
代表是否缩小，默认0代表空间不足时不会缩小，1代表空间不足时会等比例缩小。
### flex-basis
```css
.item {
  flex-basis: <length> | auto; /* default auto */
}
```
flex-basis定义了在计算剩余空间之前子元素默认的大小。可以设置为某个长度（e.g. 20%, 5rem, etc.）或者关键字。关键字**auto**意味着子元素会按照其本来的大小显示。
### flex\
默认值 
- flex-grow:0
- flex-shrink:1
- flex-basis:auto
![image](https://user-images.githubusercontent.com/25914590/43559631-5dc1bc1c-9641-11e8-8291-8e8b474c94b1.png)
- **auto**元素会根据自身的宽度与高度来确定尺寸，但是会自行伸长以吸收flex容器中额外的自由空间，也会缩短至自身最小尺寸以适应容器。这相当于将属性设置为 "flex: 1 1 auto".
- **binitial**属性默认值， 元素会根据自身宽高设置尺寸。它会缩短自身以适应容器，但不会伸长并吸收flex容器中的额外自由空间来适应容器 。相当于将属性设置为"flex: 0 1 auto"。
- **none**元素会根据自身宽高来设置尺寸。它是完全非弹性的：既不会缩短，也不会伸长来适应flex容器。相当于将属性设置为"flex: 0 0 auto"
### 圣杯布局
<div align=center>
![image](https://user-images.githubusercontent.com/25914590/43559934-d16a7aae-9642-11e8-816f-10b71d757ab4.png)
</div>
```
<body class="HolyGrail">
  <header>...</header>
  <div class="HolyGrail-body">
    <main class="HolyGrail-content">...</main>
    <nav class="HolyGrail-nav">...</nav>
    <aside class="HolyGrail-ads">...</aside>
  </div>
  <footer>...</footer>
</body>
```
